### ISSUE TITLE
ip2proxy support?

### ISSUE THREAD

**Issue by sbacelic** [ip2location/logstash-filter-ip2location#2]
Do you plan to add ip2proxy support?

**Comment by ip2location-com** [comment]
Hi @sbacelic,
Yes, we are working on it. Please feel free to follow our facebook at https://www.facebook.com/ip2location for the announcement.

**Comment by ip2location-com** [comment]
@sbacelic We are glad to inform you that IP2Proxy Filter plugin for Logstash is now available on https://github.com/ip2location/logstash-filter-ip2proxy

**Comment by sbacelic** [comment]
😄 👍 thanks!
