### ISSUE TITLE
custom  config "target"  do not take effect

### ISSUE THREAD

**Issue by zhangliming3825** [ip2location/logstash-filter-ip2location#21]
hi, create logstash  config like :
filter {
  mutate {
    remove_field => ["time"]
  }
    ip2location {
	source  => "ip"
	target => "geoip"
	database => "/var/lib/logstash/IP2LOCATION-LITE-DB11.BIN"
     }
     ip2location {
	source  => "primary_ip"
	target => "geoip_dst"
	database => "/var/lib/logstash/IP2LOCATION-LITE-DB11.BIN"
     }

      mutate {
          convert => [ "[geoip][coordinates]", "float"]
    }

  }

but i get output like as following
{

           "primary_ip" => "183.136.212.45",
          "ip2location" => {
                    "latitude" => 30.01102066040039,
                        "city" => "Shaoxing",
                "country_long" => "China",
                "mobile_brand" => "Not_Supported",
                   "net_speed" => "Not_Supported",
                  "ip_address" => "183.136.212.45",
                   "time_zone" => "+08:00",
                  "usage_type" => "Not_Supported",
                    "idd_code" => "Not_Supported",
                   "elevation" => 0.0,
                      "region" => "Zhejiang",
                         "mcc" => "Not_Supported",
                         "isp" => "Not_Supported",
        "weather_station_name" => "Not_Supported",
               "country_short" => "CN",
                    "zip_code" => "330601",
        "weather_station_code" => "Not_Supported",
                   "longitude" => 120.571533203125,
                   "area_code" => "Not_Supported",
                         "mnc" => "Not_Supported",
                      "domain" => "Not_Supported"
    },
                 
                   "ip" => "117.135.113.34"
}

the  config "target"   doesn't seem to work

**Comment by ip2location-com** [comment]
Kindly get the latest version and try it again.

Thank you.
