### ISSUE TITLE
how to install logstash-filter-ip2location offline?

### ISSUE THREAD

**Issue by zqc0512** [ip2location/logstash-filter-ip2location#4]
how to install logstash-filter-ip2location offline?
the machine can't connect to the internet ? 
how can istall this plugins offline? can give a zip file?

**Comment by zqc0512** [comment]
use clone and down the .zip file? 
where to down the plugin zip file

**Comment by ip2location-com** [comment]
You may get the logstash-filter-ip2location gems from [https://rubygems.org/gems/logstash-filter-ip2location](https://rubygems.org/gems/logstash-filter-ip2location)

**Comment by zqc0512** [comment]
@ip2location   
install with logstash-plugin install file:///xxx.gem ?
or with gem install  which directory to running gem install  logstash-filter-ip2location?
thanks.
