### ISSUE TITLE
can't show the map in kibana with ip2location

### ISSUE THREAD

**Issue by zqc0512** [ip2location/logstash-filter-ip2location#7]
when create the map. can't show data about it. how can do it?
![image](https://user-images.githubusercontent.com/25192261/38232735-c4df7e3a-374a-11e8-9980-a3a022752ba4.png)

with geoip.location can show it.
![image](https://user-images.githubusercontent.com/25192261/38232787-e36d8ae0-374a-11e8-91e0-2e3d478697d8.png)

link:
https://discuss.elastic.co/t/kibana-can-with-other-geoip-with-create-maps/126494/3

**Comment by vitich** [comment]
What type of this field? Shoud be geo_point

**Comment by zqc0512** [comment]
@vitich 
i use the mapping like this? it ok?
        "geoip": {
          "dynamic": true,
          "properties": {
            "location": {
              "type": "geo_point"
            },
            "ip": {
              "type": "ip"
            },
            "continent_code": {
              "type": "text"
            },
            "country_name": {
              "type": "text"
            }
          },
          "type": "object"
        },
        "ip2location": {
          "dynamic": true,
          "properties": {
            "location": {
              "type": "geo_point"
            },
            "ip": {
              "type": "ip"
            },
            "continent_code": {
              "type": "text"
            },
            "country_name": {
              "type": "text"
            }
          },
          "type": "object"
        },

**Comment by zqc0512** [comment]
can give me a right mapping about the ip2location  thanks.
@vitich @ip2location

**Comment by zqc0512** [comment]
@vitich @ip2location 
can give me a IP2LOCATION-LITE-DB11.BIN file?
in lite.ip2location.com  i can't register an account .
thanks.

**Comment by vitich** [comment]
@zqc0512 
https://fex.net/280356194692?fileId=396198041

**Comment by zqc0512** [comment]
@vitich  the mapping with me is ok?
can give me your right mapping?
thanks.

**Comment by zqc0512** [comment]
@vitich  @ip2location 
i see geo location have muber 

![image](https://user-images.githubusercontent.com/25192261/38283190-468d94ac-37e7-11e8-9f3b-2ce7a4725202.png)

but don't find ip2location.location filed
![image](https://user-images.githubusercontent.com/25192261/38283235-796b1854-37e7-11e8-91b4-9fb3b1626d4d.png)

**Comment by vitich** [comment]
https://discuss.elastic.co

**Comment by zqc0512** [comment]
@vitich  you have DB24.BIN file?
can give me ?
i find the ip2lcation can't add **ip2location.location** field as **geo_point** show the map can't use in kibana map 
as elastic  i also ask a question
https://discuss.elastic.co/t/kibana-can-with-other-geoip-with-create-maps/126494

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version 2.1.4.
