### ISSUE TITLE
with this filter can add a field as type geo_point ip2location.location

### ISSUE THREAD

**Issue by zqc0512** [ip2location/logstash-filter-ip2location#8]
with this filter can add a field as type geo_point
i can't use this filter see the maps in kibana  i find  this filter don't add ip2location.location type is geo_point   like the elastic give gepip filter
if not the logstash-filter-ip2location can't use success.
thanks.
@ip2location

**Comment by ip2location-com** [comment]
Kindly try it again with the latest version 2.1.4.
